version: '2.4'
services:
  
  rspamd-app:
    image: tiredofit/rspamd
    container_name: rspamd-app
    ports: 
      - 11333:11333
      - 11334:11334
    volumes:
      - ./logs/rspamd:/logs/rspamd
      - ./data/rspamd:/data/rspamd
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=rspamd-app

      - CONTROLLER_PASS=password

      - REDIS_HOST=rspamd-redis
      - CLAMAV_HOST=clamd
      - CLAMAV_PORT=3310
    networks:
      - internal
      - services
    restart: always

  rspamd-redis:
    container_name: rspamd-redis
    image: tiredofit/redis:7-latest
    volumes:
      - ./db/rspamd-redis:/var/lib/redis:Z
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=rspamd-redis
    networks:
      - internal
      - services
    restart: always


networks:
  internal:
    external: false
  services:
    external: true

