version: '2'

services:
  
  rspamd-app:
    image: tiredofit/rspamd
    container_name: rspamd-app
    ports: 
    - 11333:11333
    - 11334:11334
    volumes:
    - ./logs/rspamd:/var/log/rspamd
    - ./conf:/var/lib/rspamd
    environment:
    - ZABBIX_HOSTNAME=rspamd-app

    - ADMIN_PASS=password

    - REDIS_HOST=rspamd-redis
    - CLAMAV_HOST=clamd
    networks:
      - proxy-tier
    restart: always

  rspamd-redis:
    container_name: rspamd-redis
    restart: always
    image: tiredofit/redis
    volumes:
    - ./redis:/var/lib/redis:Z
    environment:
    - ZABBIX_HOSTNAME=rspamd-redis
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy

